### ISSUE TITLE
XLSXML - corrupt file

### ISSUE THREAD

**Issue by pro-ankita-agrawal** [beartums/yaaas#6]
Hi, 
I am using alasql in my angular 4 project for downloading xls file with formatting. this is working but when i am opening the file it says 'The file you are trying to open 'filename.xls' has a different format than specified by the extension. Verify that the file is not corrupted and it is from a trusted source before opening the file.Do you want to open the file now?'

i dont want to show this warning to my client..is this bug or what?

 let mystyle = {
      headers: true,
      column: {
        style:{
          Font:{
            Bold:"1",
            Color:"#DCDCDC",
            Size: "10"
          }
        }
      }
    };
    alasql( 'SELECT * INTO XLSXML("' + fileName + '",?) FROM ?', [mystyle,json] );

**Comment by beartums** [comment]
That's a good question.  I haven't had time to look into it, but I think I remember that naming the file as *.xlsx might fix the problem.
